sudo: false
language: node_js
node_js:
  - '0.12'
before_script:
  - 'npm install -g bower grunt-cli tsd'
  - 'cd backend'
  - 'npm install'
  - 'tsd rate'
  - 'tsd install'
  - 'grunt test'
  - 'cd ../frontend'
  - 'npm install'
  - 'bower install'
  - 'grunt test'
